Rails:
  Enabled: true

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.4
  # RuboCop has a bunch of cops enabled by default. This setting tells RuboCop
  # to ignore them, so only the ones explicitly set in this file are enabled.
  # DisabledByDefault: true
  Exclude:
    - 'bin/*'
    - '*/templates//'
    - '*/vendor//'
    - 'actionpack/lib/action_dispatch/journey/parser.rb'
    - 'railties/test/fixtures/tmp/*/'
    - 'db/schema.rb'
    - 'config/initializers/simple_form.rb'
    - 'config/initializers/simple_form_bootstrap.rb'
    - 'config/initializers/devise.rb'

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Metrics/LineLength:
  Max: 100
  Exclude:
    - 'config/environments/production.rb'
    - 'config/initializers/backtrace_silencers.rb'
    - 'config/initializers/content_security_policy.rb'

Metrics/AbcSize:
  Max: 30

Metrics/MethodLength:
  Max: 15

Bundler/OrderedGems:
  Enabled: false

Style/ExpandPathArguments:
  Exclude:
    - 'bin/*'
    - 'spec/rails_helper.rb'

Style/StringLiterals:
  Exclude:
    - 'bin/*'
    - 'config/puma.rb'
    - 'config/environments/production.rb'

Style/StderrPuts:
  Exclude:

Style/BlockComments:
  Exclude:
    - 'spec/spec_helper.rb'

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/environments/production.rb'

Style/NumericLiterals:
  Exclude:
    - 'config/puma.rb'

Rails/OutputSafety:
  Exclude:
    - 'lib/builders/bootstrap_breadcrumbs_builder.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/populate.rake'
    - 'spec/features/**/*'
    - 'config/routes.rb'

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Exclude:
    - 'spec/features/**/*'

RSpec/HookArgument:
  EnforcedStyle: each

RSpec/MissingExampleGroupArgument:
  Exclude:
    - 'spec/factories/galleries.rb'

RSpec/EmptyExampleGroup:
  Exclude:
    - 'spec/factories/galleries.rb'
